/*
SQLyog Enterprise - MySQL GUI v8.18 
MySQL - 5.5.16 
*********************************************************************
*/
/*!40101 SET NAMES utf8 */;

create table `dfck_map_thuoc` (
	`product_encoder` double ,
	`product_name` varchar (765)
); 
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('3','Combivent 0.5mg/2.5ml9salbu+Itratrobium)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('5','Celecoxib 200mg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('14','Ventolin 5mg(salbutamol ned)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('18','acetylcystein 200mg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('22','Acyclovir 800mg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('23','Pd Acyclovir 10g');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('24','Adrenalin 1mg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('28','Allopurinol 300mg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('34','RIMILO(amlodipin 5mg)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('39','Acid Acetylsalicylic(Aspirin  81mg)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('47','Bromhexin 8mg (Disolvan)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('52','Captopril 25mg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('54','CEPLOR(Cefaclor 250mg)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('57','Cefixim 100mg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('70','Chlopheniramin 4mg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('75','Ciprofloxacin 500mg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('80','Colchicin 1mg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('88','Diazepam5mg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('89','Diclofenac 50mg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('98','Efferalgan 150mg(paracetamol)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('100','ENAMIGAL 5mg(enalapril)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('109','Furosemid40mg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('112','Glucosamin 500mg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('117','Alendronat Na 70mg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('126','Ketoconazol 200mg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('127','Ketoconazol 5g');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('129','Loperamid 2mg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('131','Losartan 25mg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('138','Mephenesin 500mg (mephenesin)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('140','Methyl dopa 250mg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('144','Midazolam 5mg/ml');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('154','Nitroglycerin 2.5mg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('159','Nystatin 500.000');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('166','Pantoprazol 40mg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('173','Mypara(paracetamol 500mg)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('180','Clopidrogel 75mg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('181','Prednisolon 5mg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('182','Primperan 10mg(metoclopramide)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('191','Salbutamol 2mg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('197','Smecta(diosmetite 3g)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('205','Terpin codein');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('213','Trimafort');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('214','VASHASAN MR(trimetazidin 35mg)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('220','Vitamin  B6 0,25g');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('222','Vitamin  C 0,5g');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('223','Vitamin E 400IU');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('225','Acyclovir 200mg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('232','Cimetidin 300mg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('234','Daflon 500mg(Trimebutin+Ruscogenes)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('236','Furosemid 20mg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('297','Adrenoxy 10 mg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('301','KAVASDIN(Amlodipin 5mg)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('302','Amoxycillin 0,25g');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('311','Hyoscine - N-  butyl bromide 20mg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('314','Siro Ceelin 30ml');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('315','Cefaclor 125mg(Traclor)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('316','Cefalexin 0.5g');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('318','Cefixim 200mg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('320','Ciprofloxacin 0.3%');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('321','Calcitonic');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('322','Concor 2,5mg(Bisoprolol)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('323','Colpotrophine');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('325','Bisoprotol 5mg(Cardicormekophar)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('331','Dextromethorphan 15mg(Rodilar)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('332','Diamicron MR 30mg(Gliclazid)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('333','Gliclazide  80mg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('334','Diamicron MR 60mg(Gliclazic)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('335','Diaphylin 4.8%');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('336','Diclofenac 75 mg(Volden)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('337','Digoxin 0,25mg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('339','Pethidin 100MG/2ml');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('341','Doxycillin 100 mg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('342','Dumazil (Almitrine+Raubasine )');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('347','FENOSUP LIDOSE (fenofibrat 160mg)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('348','Fentanyl 0.1mg/2ml');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('351','Metronidazol  0,25 g');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('352','Fluconazol 150mg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('356','Gentamycin 80mg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('357','Gingko biloba 40mg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('359','Glucosamin sñi 500mg (Siova)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('360','Glucovance 500mg/2,5(Metformin+glibenclamid)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('365','Hydrocortison 100mg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('366','Hydrite');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('370','Ketamin 50mg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('372','Lactacyd PH');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('374','Lidocain 2%');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('375','Lidocain 10%');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('376','Fenofibrat (Fenohexal 300mg)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('378','Loxoprofen (Loxfen) 60mg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('380','Melankit (lanso+tinidazol+clathri)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('382','Metformin 850mg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('384','Domitazol');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('386','Misoprostol 200mcg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('387','Morphin 10mg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('389','Naloxon 0,4mg/1ml');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('390','Natrilix 1,5mg (Indapamid)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('392','Neo- Gynoternan (h/10v)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('395','Drotaverin(Nospa 40mg)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('397','Ofloxacin  200mg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('398','Oflovid sol 5ml');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('404','Oxy giµ');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('408','Phezam (Piracetam 400+ Cinarizin 25)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('410','Pipophen 50mg/2ml(promathazin)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('411','Dexchlorpheniramin 2mg(Vacopola)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('412','Povidin 90ml');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('413','Elitan(metoclopramide 10mg)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('415','Isosorbid dinitrate 5mg (Biresort)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('416','Isosorbid dinitrate 10mg (Biresort)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('417','Spiramycin 0.75M (Doropycin)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('418','Natri thiosulfat 330mg (Vaco Sulfene)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('419','Salbutamol 1mg    Suppo');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('421','Diazepam10mg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('422','Ser C 8mg (Betahistidin )');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('424','Siro bromhexin 4mg/5ml');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('425','Sorbitol 25g');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('432','Mekotyrossin');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('436','Vitamin K1 (Vidxac)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('439','Coversyl 5mg (Peridopril Arginine)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('442','O R S');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('445','AMBRON(Ambrozol 30mg)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('446','Amoxycillin 0,5g');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('447','Lactobacillus acidophilus(Lacbio pro)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('449','Atorvastatin 10mg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('452','Cefaclor 375mg (Traclor)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('454','Cefotaxim 1g(Carexime)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('458','Clarithromycin 250mg(Kalecin )');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('459','Chloramphenicol 0.4%');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('461','Bi-Preterax (Perindopril 4mg+indapamide 1,25mg)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('467','Efferalgan 300mg(paracetamol)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('468','Eprazinon 50mg(Eramux)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('469','Fe Folic (Enpovid)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('470','Forlax(Lactose 15ml)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('472','Paracetamol 150mg (AGIMOL)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('473','Hull (nh«m hydroxyd+ magnesi)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('477','Amox 500mg + acid clavulanate125mg (Cledomox 625)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('478','Lisinopril (Lisidigal) 10mg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('479','Meloxicam 7,5mg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('480','Domperidol 10mg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('481','Natri clorid 0.9%/10ml (Efticol)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('482','Nifehexan   20mg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('489','Paracetamol 0,5g  inject');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('491','Protolog suppo(Trimebutin+Ruscogenine)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('492','Agirovastin 10mg (Rosuvastatin)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('498','Vitamin  B1 0,25g');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('501','Vitamin PP');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('502','Irbesartan 150mg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('504','Coveram(perindopril,amlodipin)5-5');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('506','Diacerein 50mg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('507','Duphalac(Lactulose 15ml)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('508','Isosobid -5 mononitrat 60mg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('509','Lamivudin 100mg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('512','Newhem');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('515','Theophylin 100 mg (Theostat)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('520','Peniciliin V 400.000 UI');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('622','Metformin 500mg(Diabesel)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('630','Siro Alimemazin 90ml(themaxtene)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('653','Alfuzosin( xatral 5mg)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('660','siro Nutrolex');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('692','Devodil  50mg(sulpiride)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('694','Cloramphenicol   0,4%');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('702','Symbicort 60dose');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('704','Gabapentin 300mg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('711','acid nalidixic(Negradixid 500mg)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('713','Fexofenadin 120mg (Fefasdin)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('715','Pracetamol 650mg(PANACTOL)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('718','Acetylleucin 0,5g (Gikanin)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('723','Spiramycin 3MIU(Spibiotic)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('742','Subtyl (bacilus subtilis)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('754','Topralsin');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('766','Cefpodoxim 100mg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('774','Alphachymotrypsin(Medo-alpha)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('813','Omeprazole 20mg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('814','Paracetamo 500mgl+codein30mg(Eftimol)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('819','Mage-B6(MAGDIVIX)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('820','Grangel Susp');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('829','Alverin citrat 40mg(Spacmarizine)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('830','Alimemazine 5mg(Theratussine)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('834','Idarac 200mg(Floctafenin)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('858','Clopidogrel 300mg(Plavix)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('869','Ampicillin  1g');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('870','Manitol 20%');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('872','LOMINDUS(Omeprazol 40mg/ml)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('873','Glucose 30 %/5ml');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('882','Vtamin A-D');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('883','KAHEPA(Arginin 200mg)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1050','BONEVIT(calcigluconat+vitc+vitD+pp)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1054','Atenolon Denk 50mg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1055','Enaplapril 10mg(ENAMIGAL)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1059','Metformin 1000mg (Meglucon)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1074','Ceftazidim 1g');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1078','Levofloxacin 500mg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1087','Cefurocim 250mg(Tv-cefu)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1095','TAVAZID');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1096','TAVAZID SACHEST');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1098','Sulfamethoxazol+trimethroprime (Sulfaprim )');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1102','SERBUTAM(SALBUTAMOL 100MCG)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1106','SIRO DOMPERON(domperidon)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1111','BDDE 25mg(Biphenyl dimethl dicarboxylat)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1113','Aminoplasmal 15% (250ml )');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1119','Micardis 40mg (Telmisartan)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1120','Insulin lent 400UI /10ml');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1126','TUFLU (tobramycin)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1132','GINKOR (ginkobiloba+heptaminol+troxerutin)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1143','Paracetamol 250mg(Cenpadol)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1144','Ventolin 2,5mg(salbutamol neb)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1146','DUPHASTON (dydrogesteron 10mg)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1156','ALENBE(alendronat 70mg)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1157','MEMORIL FCTSB(piracetam 800mg)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1162','Seretide 250mcg xịt');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1170','Griseofulvin 500mg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1179','Acarbose 50mg (Medbose)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1180','ADDCEF(Cefdinir 300mg)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1181','AGUETTANT(Ephedrin 30mg/1ml)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1182','Atropinsulfat 0,25mg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1183','Aubactam 312.5 mg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1184','Bupivacain 50mg/20ml');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1185','Calci clorid 0.5g/5ml');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1186','Calcigluconat+calcicarbonat(Calcium VPC)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1187','Cefurocim 250mg(Tv-cefu)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1188','Cenzeal(glimepiride 2mg)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1189','Cenzeal(glimepiride 4mg)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1190','CETAMAT 250mg(cefetamet pivoxil)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1191','CETAMAT 500mg(cefetamet pivoxil)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1192','Cinarizin 25mg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1193','Citirizin 10mg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1194','CLAZIC SR 30mg(Gliclazic)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1195','Dexinacol 5ml');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1196','Dextrose  5%');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1197','ESSENTALE (phospholipid)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1198','Flumetholon');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1199','Gastropulgyte 2.5g');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1200','GRAFORT(dioctahedral smectit)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1201','Insulin b¸n chËm- bót (Insulatard Flexpen )100IUml 3ml');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1202','IRVELL(irbesartan 150mg)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1203','Lactacringer');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1204','Lanzee (Lanzoprazol + Doperidone)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1205','Levo-Thyroxin 100mcg');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1206','Maedsamic (aicd trannexamic 250 mg)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1207','Metformin 850mg(METINIM)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1208','Natriclorua 0,9% 500 ml');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1209','N­íc cÊt  5ml');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1210','Nospa 40mg(Drotaverin)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1211','Omeprazol 20mg(Dudencer)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1212','POVIDIN 10%/20ML');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1213','REFORTAN 6%');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1214','REPAMAX(paracetamol 500mg)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1215','Siro prometazin 90ml');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1216','STUFORT CAP (piracetam + cinarizin)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1217','Telmisartan 25mg(TISARTAN)');
insert into `dfck_map_thuoc` (`product_encoder`, `product_name`) values('1218','Vastaren MR 35mg(Trimatazidine)');
